# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiciancredits', '0002_recording_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_recordings', to='musiciancredits.User'),
        ),
    ]
