# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiciancredits', '0003_recording_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='player',
            field=models.ManyToManyField(related_name='played_recordings', to='musiciancredits.User'),
        ),
    ]
