# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiciancredits', '0004_recording_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='player',
            new_name='players',
        ),
    ]
