# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiciancredits', '0005_auto_20181025_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='listen',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
