# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiciancredits', '0006_recording_listen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='listen',
            new_name='spotify',
        ),
        migrations.AddField(
            model_name='recording',
            name='youtube',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
